apiVersion: v1 # Versión de la API de Kubernetes utilizada
kind: Service # Tipo de recurso que expone la aplicación en la red
metadata:
  name: mi-pagina-web-service # Nombre del Service
spec:
  type: LoadBalancer # Expone la aplicación fuera del clúster si existe un balanceador compatible
  selector:
    app.kubernetes.io/name: mi-pagina-web
  ports:
    - name: http
      protocol: TCP
      port: 8383 # Puerto de acceso al Service
      targetPort: http # Puerto HTTP nombrado del contenedor
