apiVersion: v1 # This is the API version
kind: Service # This is the kind of object we are creating
metadata: # This is the metadata of the object
  name: mi-pagina-web-service # This is the name of the object
spec: # This is the specification of the object
  type: LoadBalancer # This is the type of the object
  selector: # This is the selector of the object
    app: mi-pagina-web # This is the app of the object
  ports: # This is the ports of the object
  - protocol: TCP # This is the protocol of the port
    port: 8181 # This is the port of the object
    targetPort: 80 # This is the targetPort of the object